# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kappashung/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/kappashung/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/kapas/CLionProjects/untitled/graph2023

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/kapas/CLionProjects/untitled/graph2023

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/kappashung/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/kappashung/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/kapas/CLionProjects/untitled/graph2023/CMakeFiles /mnt/c/Users/kapas/CLionProjects/untitled/graph2023//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/kapas/CLionProjects/untitled/graph2023/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graph_server

# Build rule for target.
graph_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph_server
.PHONY : graph_server

# fast build rule for target.
graph_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/build
.PHONY : graph_server/fast

#=============================================================================
# Target rules for targets named graph_test

# Build rule for target.
graph_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph_test
.PHONY : graph_test

# fast build rule for target.
graph_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/build
.PHONY : graph_test/fast

methods/bridge_search_method.o: methods/bridge_search_method.cpp.o
.PHONY : methods/bridge_search_method.o

# target to build an object file
methods/bridge_search_method.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/methods/bridge_search_method.cpp.o
.PHONY : methods/bridge_search_method.cpp.o

methods/bridge_search_method.i: methods/bridge_search_method.cpp.i
.PHONY : methods/bridge_search_method.i

# target to preprocess a source file
methods/bridge_search_method.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/methods/bridge_search_method.cpp.i
.PHONY : methods/bridge_search_method.cpp.i

methods/bridge_search_method.s: methods/bridge_search_method.cpp.s
.PHONY : methods/bridge_search_method.s

# target to generate assembly for a file
methods/bridge_search_method.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/methods/bridge_search_method.cpp.s
.PHONY : methods/bridge_search_method.cpp.s

methods/main.o: methods/main.cpp.o
.PHONY : methods/main.o

# target to build an object file
methods/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/methods/main.cpp.o
.PHONY : methods/main.cpp.o

methods/main.i: methods/main.cpp.i
.PHONY : methods/main.i

# target to preprocess a source file
methods/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/methods/main.cpp.i
.PHONY : methods/main.cpp.i

methods/main.s: methods/main.cpp.s
.PHONY : methods/main.s

# target to generate assembly for a file
methods/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_server.dir/build.make CMakeFiles/graph_server.dir/methods/main.cpp.s
.PHONY : methods/main.cpp.s

tests/bridge_search_test.o: tests/bridge_search_test.cpp.o
.PHONY : tests/bridge_search_test.o

# target to build an object file
tests/bridge_search_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/bridge_search_test.cpp.o
.PHONY : tests/bridge_search_test.cpp.o

tests/bridge_search_test.i: tests/bridge_search_test.cpp.i
.PHONY : tests/bridge_search_test.i

# target to preprocess a source file
tests/bridge_search_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/bridge_search_test.cpp.i
.PHONY : tests/bridge_search_test.cpp.i

tests/bridge_search_test.s: tests/bridge_search_test.cpp.s
.PHONY : tests/bridge_search_test.s

# target to generate assembly for a file
tests/bridge_search_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/bridge_search_test.cpp.s
.PHONY : tests/bridge_search_test.cpp.s

tests/graph_test.o: tests/graph_test.cpp.o
.PHONY : tests/graph_test.o

# target to build an object file
tests/graph_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/graph_test.cpp.o
.PHONY : tests/graph_test.cpp.o

tests/graph_test.i: tests/graph_test.cpp.i
.PHONY : tests/graph_test.i

# target to preprocess a source file
tests/graph_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/graph_test.cpp.i
.PHONY : tests/graph_test.cpp.i

tests/graph_test.s: tests/graph_test.cpp.s
.PHONY : tests/graph_test.s

# target to generate assembly for a file
tests/graph_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/graph_test.cpp.s
.PHONY : tests/graph_test.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/oriented_graph_test.o: tests/oriented_graph_test.cpp.o
.PHONY : tests/oriented_graph_test.o

# target to build an object file
tests/oriented_graph_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/oriented_graph_test.cpp.o
.PHONY : tests/oriented_graph_test.cpp.o

tests/oriented_graph_test.i: tests/oriented_graph_test.cpp.i
.PHONY : tests/oriented_graph_test.i

# target to preprocess a source file
tests/oriented_graph_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/oriented_graph_test.cpp.i
.PHONY : tests/oriented_graph_test.cpp.i

tests/oriented_graph_test.s: tests/oriented_graph_test.cpp.s
.PHONY : tests/oriented_graph_test.s

# target to generate assembly for a file
tests/oriented_graph_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/oriented_graph_test.cpp.s
.PHONY : tests/oriented_graph_test.cpp.s

tests/test_core.o: tests/test_core.cpp.o
.PHONY : tests/test_core.o

# target to build an object file
tests/test_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/test_core.cpp.o
.PHONY : tests/test_core.cpp.o

tests/test_core.i: tests/test_core.cpp.i
.PHONY : tests/test_core.i

# target to preprocess a source file
tests/test_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/test_core.cpp.i
.PHONY : tests/test_core.cpp.i

tests/test_core.s: tests/test_core.cpp.s
.PHONY : tests/test_core.s

# target to generate assembly for a file
tests/test_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/test_core.cpp.s
.PHONY : tests/test_core.cpp.s

tests/weighted_graph_test.o: tests/weighted_graph_test.cpp.o
.PHONY : tests/weighted_graph_test.o

# target to build an object file
tests/weighted_graph_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/weighted_graph_test.cpp.o
.PHONY : tests/weighted_graph_test.cpp.o

tests/weighted_graph_test.i: tests/weighted_graph_test.cpp.i
.PHONY : tests/weighted_graph_test.i

# target to preprocess a source file
tests/weighted_graph_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/weighted_graph_test.cpp.i
.PHONY : tests/weighted_graph_test.cpp.i

tests/weighted_graph_test.s: tests/weighted_graph_test.cpp.s
.PHONY : tests/weighted_graph_test.s

# target to generate assembly for a file
tests/weighted_graph_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/weighted_graph_test.cpp.s
.PHONY : tests/weighted_graph_test.cpp.s

tests/weighted_oriented_graph_test.o: tests/weighted_oriented_graph_test.cpp.o
.PHONY : tests/weighted_oriented_graph_test.o

# target to build an object file
tests/weighted_oriented_graph_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/weighted_oriented_graph_test.cpp.o
.PHONY : tests/weighted_oriented_graph_test.cpp.o

tests/weighted_oriented_graph_test.i: tests/weighted_oriented_graph_test.cpp.i
.PHONY : tests/weighted_oriented_graph_test.i

# target to preprocess a source file
tests/weighted_oriented_graph_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/weighted_oriented_graph_test.cpp.i
.PHONY : tests/weighted_oriented_graph_test.cpp.i

tests/weighted_oriented_graph_test.s: tests/weighted_oriented_graph_test.cpp.s
.PHONY : tests/weighted_oriented_graph_test.s

# target to generate assembly for a file
tests/weighted_oriented_graph_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_test.dir/build.make CMakeFiles/graph_test.dir/tests/weighted_oriented_graph_test.cpp.s
.PHONY : tests/weighted_oriented_graph_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... graph_server"
	@echo "... graph_test"
	@echo "... methods/bridge_search_method.o"
	@echo "... methods/bridge_search_method.i"
	@echo "... methods/bridge_search_method.s"
	@echo "... methods/main.o"
	@echo "... methods/main.i"
	@echo "... methods/main.s"
	@echo "... tests/bridge_search_test.o"
	@echo "... tests/bridge_search_test.i"
	@echo "... tests/bridge_search_test.s"
	@echo "... tests/graph_test.o"
	@echo "... tests/graph_test.i"
	@echo "... tests/graph_test.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/oriented_graph_test.o"
	@echo "... tests/oriented_graph_test.i"
	@echo "... tests/oriented_graph_test.s"
	@echo "... tests/test_core.o"
	@echo "... tests/test_core.i"
	@echo "... tests/test_core.s"
	@echo "... tests/weighted_graph_test.o"
	@echo "... tests/weighted_graph_test.i"
	@echo "... tests/weighted_graph_test.s"
	@echo "... tests/weighted_oriented_graph_test.o"
	@echo "... tests/weighted_oriented_graph_test.i"
	@echo "... tests/weighted_oriented_graph_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

